import type {Metadata} from "next";
import "./globals.css";
import {Footer} from "@/components/Footer";
import {Inter as FontSans} from "next/font/google"
import React from "react";
import localFont from "next/font/local";
import {cn} from "@/lib/utils";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const proximaNova = localFont({
    src: [
        {
            path: '../.././public/fonts/proximanova_bold.otf',
            weight: '700',
            style: 'normal',
        },
        {
            path: '../../public/fonts/proximanova_regular.ttf',
            weight: '400',
            style: 'normal',
        },
    ],
    display: "swap",
    variable: "--font-proxima"
})

const fontSans = FontSans({
    subsets: ["latin", "cyrillic"],
    variable: "--font-sans",
})
export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="ru" className={`scroll-smooth ${proximaNova.variable}`}>
        <body className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
        )}>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
